ARG BASE_IMAGE="ubuntu:18.04"
ARG PKG_TAR=".temp_dockerbuild/flir_client_x86_pkg.tar"
FROM $BASE_IMAGE

# Copy setup script to image
COPY ./docker ./docker
COPY .temp_dockerbuild/flir_client_x86_pkg.tar ./
COPY ./scripts/setup_environment.sh ./scripts/setup_environment.sh
RUN ./scripts/setup_environment.sh
RUN tar -xf flir_client_x86_pkg.tar
CMD ["/bin/flirone_over_post", "/launch.json"]
