// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: interfaces/flirone_image.proto
#ifndef GRPC_interfaces_2fflirone_5fimage_2eproto__INCLUDED
#define GRPC_interfaces_2fflirone_5fimage_2eproto__INCLUDED

#include "interfaces/flirone_image.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class FlirOneImageService final {
 public:
  static constexpr char const* service_full_name() {
    return "FlirOneImageService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SubmitImage(::grpc::ClientContext* context, const ::FlirOneImage& request, ::common::Void* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::Void>> AsyncSubmitImage(::grpc::ClientContext* context, const ::FlirOneImage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::Void>>(AsyncSubmitImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::Void>> PrepareAsyncSubmitImage(::grpc::ClientContext* context, const ::FlirOneImage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::common::Void>>(PrepareAsyncSubmitImageRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void SubmitImage(::grpc::ClientContext* context, const ::FlirOneImage* request, ::common::Void* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SubmitImage(::grpc::ClientContext* context, const ::FlirOneImage* request, ::common::Void* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SubmitImage(::grpc::ClientContext* context, const ::FlirOneImage* request, ::common::Void* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::common::Void>* AsyncSubmitImageRaw(::grpc::ClientContext* context, const ::FlirOneImage& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::common::Void>* PrepareAsyncSubmitImageRaw(::grpc::ClientContext* context, const ::FlirOneImage& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SubmitImage(::grpc::ClientContext* context, const ::FlirOneImage& request, ::common::Void* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::Void>> AsyncSubmitImage(::grpc::ClientContext* context, const ::FlirOneImage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::Void>>(AsyncSubmitImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::Void>> PrepareAsyncSubmitImage(::grpc::ClientContext* context, const ::FlirOneImage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::common::Void>>(PrepareAsyncSubmitImageRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void SubmitImage(::grpc::ClientContext* context, const ::FlirOneImage* request, ::common::Void* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SubmitImage(::grpc::ClientContext* context, const ::FlirOneImage* request, ::common::Void* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SubmitImage(::grpc::ClientContext* context, const ::FlirOneImage* request, ::common::Void* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::common::Void>* AsyncSubmitImageRaw(::grpc::ClientContext* context, const ::FlirOneImage& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::common::Void>* PrepareAsyncSubmitImageRaw(::grpc::ClientContext* context, const ::FlirOneImage& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SubmitImage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SubmitImage(::grpc::ServerContext* context, const ::FlirOneImage* request, ::common::Void* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SubmitImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SubmitImage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SubmitImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitImage(::grpc::ServerContext* /*context*/, const ::FlirOneImage* /*request*/, ::common::Void* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitImage(::grpc::ServerContext* context, ::FlirOneImage* request, ::grpc::ServerAsyncResponseWriter< ::common::Void>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SubmitImage<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_SubmitImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_SubmitImage() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::FlirOneImage, ::common::Void>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::FlirOneImage* request, ::common::Void* response) { return this->SubmitImage(context, request, response); }));}
    void SetMessageAllocatorFor_SubmitImage(
        ::grpc::experimental::MessageAllocator< ::FlirOneImage, ::common::Void>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::FlirOneImage, ::common::Void>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_SubmitImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitImage(::grpc::ServerContext* /*context*/, const ::FlirOneImage* /*request*/, ::common::Void* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SubmitImage(
      ::grpc::CallbackServerContext* /*context*/, const ::FlirOneImage* /*request*/, ::common::Void* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SubmitImage(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::FlirOneImage* /*request*/, ::common::Void* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_SubmitImage<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_SubmitImage<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SubmitImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SubmitImage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SubmitImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitImage(::grpc::ServerContext* /*context*/, const ::FlirOneImage* /*request*/, ::common::Void* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SubmitImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SubmitImage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SubmitImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitImage(::grpc::ServerContext* /*context*/, const ::FlirOneImage* /*request*/, ::common::Void* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubmitImage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_SubmitImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_SubmitImage() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SubmitImage(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_SubmitImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SubmitImage(::grpc::ServerContext* /*context*/, const ::FlirOneImage* /*request*/, ::common::Void* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SubmitImage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SubmitImage(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SubmitImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SubmitImage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::FlirOneImage, ::common::Void>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::FlirOneImage, ::common::Void>* streamer) {
                       return this->StreamedSubmitImage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SubmitImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SubmitImage(::grpc::ServerContext* /*context*/, const ::FlirOneImage* /*request*/, ::common::Void* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSubmitImage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::FlirOneImage,::common::Void>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SubmitImage<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SubmitImage<Service > StreamedService;
};


#endif  // GRPC_interfaces_2fflirone_5fimage_2eproto__INCLUDED
