package(
    default_visibility = ["//visibility:public"],
)

cc_test(
    name = "test_encryption_utils",
    srcs = ["test_encryption_utils.cc"],
    deps = [
      "//common:encryption_utils",
      "@gtest//:gtest",
      "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "test_config_utils",
    srcs = ["test_config_utils.cc"],
    deps = [
      "//common:config_utils",
      "@gtest//:gtest",
      "@gtest//:gtest_main",
    ],
)
